/**
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed.ql.impl;

import com.b2international.snowowl.snomed.ql.Exclusion;
import com.b2international.snowowl.snomed.ql.QlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exclusion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExclusionImpl extends ConjunctionImpl implements Exclusion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExclusionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QlPackage.Literals.EXCLUSION;
  }

} //ExclusionImpl
