/**
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed.ql.impl;

import com.b2international.snowowl.snomed.ql.Disjunction;
import com.b2international.snowowl.snomed.ql.QlPackage;
import com.b2international.snowowl.snomed.ql.Query;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.b2international.snowowl.snomed.ql.impl.QueryImpl#getDisjunction <em>Disjunction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QueryImpl extends MinimalEObjectImpl.Container implements Query
{
  /**
   * The cached value of the '{@link #getDisjunction() <em>Disjunction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisjunction()
   * @generated
   * @ordered
   */
  protected Disjunction disjunction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QueryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QlPackage.Literals.QUERY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Disjunction getDisjunction()
  {
    return disjunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDisjunction(Disjunction newDisjunction, NotificationChain msgs)
  {
    Disjunction oldDisjunction = disjunction;
    disjunction = newDisjunction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QlPackage.QUERY__DISJUNCTION, oldDisjunction, newDisjunction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDisjunction(Disjunction newDisjunction)
  {
    if (newDisjunction != disjunction)
    {
      NotificationChain msgs = null;
      if (disjunction != null)
        msgs = ((InternalEObject)disjunction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QlPackage.QUERY__DISJUNCTION, null, msgs);
      if (newDisjunction != null)
        msgs = ((InternalEObject)newDisjunction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QlPackage.QUERY__DISJUNCTION, null, msgs);
      msgs = basicSetDisjunction(newDisjunction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QlPackage.QUERY__DISJUNCTION, newDisjunction, newDisjunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QlPackage.QUERY__DISJUNCTION:
        return basicSetDisjunction(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QlPackage.QUERY__DISJUNCTION:
        return getDisjunction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QlPackage.QUERY__DISJUNCTION:
        setDisjunction((Disjunction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QlPackage.QUERY__DISJUNCTION:
        setDisjunction((Disjunction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QlPackage.QUERY__DISJUNCTION:
        return disjunction != null;
    }
    return super.eIsSet(featureID);
  }

} //QueryImpl
