path_classifiers:
  library:
    - core/com.b2international.snowowl.core.rest/site
    - core/com.b2international.snowowl.core.rest/snow-owl-api-docs
extraction:
  java:
    before_index:
      - "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
    index:
      maven:
        version: 3.6.3