path_classifiers:
  library:
    - cis/com.b2international.snowowl.snomed.cis.rest/static/lib
    - core/com.b2international.snowowl.api.rest/static/lib
    - core/com.b2international.snowowl.fhir.api/static/lib
    - snomed/com.b2international.snowowl.snomed.api.rest/static/lib
extraction:
  java:
    before_index:
      - "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
    index:
      maven:
        version: 3.5.3