<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="snomedrefset" nsURI="http://b2international.com/snowowl/snomed/refset/1.0"
    nsPrefix="sctrefset">
  <eClassifiers xsi:type="ecore:EClass" name="SnomedRefSet" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SnomedRefSetType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedComponentType"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifierId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedRegularRefSet" eSuperTypes="#//SnomedRefSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" ordered="false"
        upperBound="-1" eType="#//SnomedRefSetMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedStructuralRefSet" eSuperTypes="#//SnomedRefSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedMappingRefSet" eSuperTypes="#//SnomedRegularRefSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapTargetComponentType"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedConcreteDataTypeRefSet" eSuperTypes="#//SnomedStructuralRefSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedComponentType"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refSet" lowerBound="1"
        eType="#//SnomedRefSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="released" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedComponentId"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refSetIdentifierId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        transient="true" defaultValueLiteral="" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedDescriptionTypeRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionFormat" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedSimpleMapRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapTargetComponentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapTargetComponentType"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapTargetComponentDescription"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedComplexMapRefSetMember" eSuperTypes="#//SnomedSimpleMapRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapGroup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapPriority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapRule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnType" value="LONG VARCHAR"/>
        <details key="columnLength" value="32768"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapAdvice" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnType" value="LONG VARCHAR"/>
        <details key="columnLength" value="32768"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correlationId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapCategoryId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedQueryRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedAttributeValueRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedLanguageRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptabilityId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedConcreteDataTypeRefSetMember"
      eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializedValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnName" value="label0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uomComponentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorComponentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataType" changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characteristicTypeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedAssociationRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetComponentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetComponentType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort" changeable="false"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SnomedRefSetType">
    <eLiterals name="SIMPLE"/>
    <eLiterals name="SIMPLE_MAP" value="1"/>
    <eLiterals name="LANGUAGE" value="2"/>
    <eLiterals name="ATTRIBUTE_VALUE" value="3"/>
    <eLiterals name="QUERY" value="4"/>
    <eLiterals name="COMPLEX_MAP" value="5"/>
    <eLiterals name="DESCRIPTION_TYPE" value="6" literal="DESCRIPTION_TYPE"/>
    <eLiterals name="CONCRETE_DATA_TYPE" value="7" literal="CONCRETE_DATA_TYPE"/>
    <eLiterals name="ASSOCIATION" value="8"/>
    <eLiterals name="MODULE_DEPENDENCY" value="9" literal="MODULE_DEPENDENCY"/>
    <eLiterals name="EXTENDED_MAP" value="10" literal="EXTENDED_MAP"/>
    <eLiterals name="ANNOTATION" value="11" literal="ANNOTATION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="INTEGER" literal="INTEGER"/>
    <eLiterals name="DECIMAL" value="1" literal="DECIMAL"/>
    <eLiterals name="BOOLEAN" value="2" literal="BOOLEAN"/>
    <eLiterals name="DATE" value="3" literal="DATE"/>
    <eLiterals name="STRING" value="4" literal="STRING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedModuleDependencyRefSetMember"
      eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceEffectiveTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetEffectiveTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedAnnotationRefSetMember" eSuperTypes="#//SnomedRefSetMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnType" value="LONG VARCHAR"/>
        <details key="columnLength" value="32768"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
