/**
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed.ql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conjunction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.b2international.snowowl.snomed.ql.QlPackage#getConjunction()
 * @model
 * @generated
 */
public interface Conjunction extends Disjunction
{
} // Conjunction
