/**
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed.ql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Term Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.b2international.snowowl.snomed.ql.TermFilter#getTerm <em>Term</em>}</li>
 * </ul>
 *
 * @see com.b2international.snowowl.snomed.ql.QlPackage#getTermFilter()
 * @model
 * @generated
 */
public interface TermFilter extends Filter
{
  /**
   * Returns the value of the '<em><b>Term</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Term</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' attribute.
   * @see #setTerm(String)
   * @see com.b2international.snowowl.snomed.ql.QlPackage#getTermFilter_Term()
   * @model
   * @generated
   */
  String getTerm();

  /**
   * Sets the value of the '{@link com.b2international.snowowl.snomed.ql.TermFilter#getTerm <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' attribute.
   * @see #getTerm()
   * @generated
   */
  void setTerm(String value);

} // TermFilter
