/*
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class QLRuntimeModule extends AbstractQLRuntimeModule {
}
