<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mrcm" nsURI="http://b2international.com/snowowl/snomed/mrcm"
    nsPrefix="mrcm">
  <eClassifiers xsi:type="ecore:EClass" name="ConceptModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The top-level container for various types of constraints."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ConstraintBase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptModelComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for various concept model components."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptModelPredicate" abstract="true"
      eSuperTypes="#//ConceptModelComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for concept model predicates."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CardinalityPredicate" eSuperTypes="#//ConceptModelPredicate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Predicate representing an MRCM cardinality check."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupRule" lowerBound="1"
        eType="#//GroupRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
        eType="#//ConceptModelPredicate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteDomainElementPredicate" eSuperTypes="#//ConceptModelPredicate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Predicate to check for the presence of a concrete model element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//ConceptSetDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characteristicTypeConceptId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyPredicate" eSuperTypes="#//ConceptModelPredicate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Predicate to check for a group of child predicates."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ConceptModelPredicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//DependencyOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupRule" lowerBound="1"
        eType="#//GroupRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionPredicate" eSuperTypes="#//ConceptModelPredicate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Predicate to check for the presence of a description of a specific type (e.g. fully specified name, synonym, etc.)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipPredicate" eSuperTypes="#//ConceptModelPredicate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Predicate to check for a relationship with the specified type and value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//ConceptSetDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" eType="#//ConceptSetDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characteristicTypeConceptId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptSetDefinition" abstract="true"
      eSuperTypes="#//ConceptModelComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a set of concepts, specified based on different kinds of criteria."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeConceptSetDefinition" eSuperTypes="#//ConceptSetDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a composite concept set definition."/>
    </eAnnotations>
    <eOperations name="addChild" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="child" lowerBound="1" eType="#//ConceptSetDefinition"/>
    </eOperations>
    <eOperations name="removeChild" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="child" lowerBound="1" eType="#//ConceptSetDefinition"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ConceptSetDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedConceptSetDefinition" eSuperTypes="#//ConceptSetDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Concept set definition for explicitly enumerating the included concepts."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptIds" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HierarchyConceptSetDefinition" eSuperTypes="#//ConceptSetDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Concept set definition for including a concept and/or its subtypes.                                       &#xD;&#xA;&lt;p>Examples:                                                                                              &#xD;&#xA;&lt;ul>                                                                                                      &#xD;&#xA;&lt;li>= 373873005 -> &lt;i>Pharamaceutical / biologic product&lt;/i>&lt;/li>                                         &#xD;&#xA;&lt;li>&lt; 373873005 -> all subtypes of &lt;i>Pharamaceutical / biologic product&lt;/i>&lt;/li>                         &#xD;&#xA;&lt;li>&lt;&lt; 900000000000454005 -> all descendants of &lt;i>Foundation metadata concepts&lt;/i>, including itself&lt;/li>&#xD;&#xA;&lt;/ul>                                                                                                     &#xD;&#xA;&#xD;&#xA;@author zstorok"/>
    </eAnnotations>
    <eOperations name="getFocusConceptId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inclusionType" lowerBound="1"
        eType="#//HierarchyInclusionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceSetConceptSetDefinition" eSuperTypes="#//ConceptSetDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Concept set definition for using the members of an existing concept reference set."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refSetIdentifierConceptId"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipConceptSetDefinition" eSuperTypes="#//ConceptSetDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Concept set definition describing concepts which include a relationship of the given type and destination."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeConceptId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationConceptId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintBase" abstract="true" eSuperTypes="#//ConceptModelComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for concept model constraints."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strength" lowerBound="1"
        eType="#//ConstraintStrength"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraint" eSuperTypes="#//ConstraintBase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents an constraint on an attribute (e.g. relationship or description) of a concept."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="form" lowerBound="1" eType="#//ConstraintForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//ConceptSetDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
        eType="#//ConceptModelPredicate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupRule">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Indicates whether a predicate applies to ungrouped relationships, relationships in a group, all relationships or a set of groups."/>
    </eAnnotations>
    <eLiterals name="UNGROUPED" literal="UNGROUPED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Test cardinality or interdependency between ungrouped relationships."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SINGLE_GROUP" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Test cardinality or interdependency between Relationships in each relationship group."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ALL_GROUPS" value="2" literal="ALL_GROUPS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Test cardinality or interdependency between all relationships irrespective of whether they are grouped or ungrouped."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MULTIPLE_GROUPS" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Test cardinality or interdependency between relationship groups that match the predicates in the referenced dependency predicate."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DependencyOperator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Indicates how many child predicates of a dependency predicate are required to be true."/>
    </eAnnotations>
    <eLiterals name="ONE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return true if one and only one child predicate in the composite predicate returns true."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SOME" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return true if at least one child predicate in the composite predicate returns true."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ALL" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return true if all tests in the composite predicate return true."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HierarchyInclusionType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Indicates whether the given concept and/or its subtypes are included in a concept set definition."/>
    </eAnnotations>
    <eLiterals name="SELF">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Include the specified concept."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DESCENDANT" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Include subtype descendants of the specified concept."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SELF_OR_DESCENDANT" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Include the specified concept and all its subtype concepts."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CHILD" value="3" literal="CHILD">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Include the direct children of the specified concept."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintStrength">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Indicates the strength and applicability of a constraint."/>
    </eAnnotations>
    <eLiterals name="MANDATORY_CM">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Mandatory concept model constraint."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RECOMMENDED_CM" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Recommended concept model constraint based on best practice editorial rules."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ADVISORY_CM" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Advisory concept model constraint based on editorial conventions."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MANDATORY_PC" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Mandatory constraint on post-coordinated refinement."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="INFORMATION_MODEL_PC" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constraint of post-coordinated refinement that is specific to use in a particular information model. The information model is identified by the 'scope' attribute."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="USE_CASE_SPECIFIC_PC" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constraint of post-coordinated refinement that is specific to a particular use case. The use case is identified by the 'scope' attribute."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="IMPLEMENTATION_SPECIFIC_PC" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constraint of post-coordinated refinement that is specific to a particular application or local implementation. The implementation is identified by the 'scope' attribute."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintForm">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Indicates the model or post-coordinated form to which a constraint applies."/>
    </eAnnotations>
    <eLiterals name="ALL_FORMS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraint should be true in all forms."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DISTRIBUTION_FORM" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraint should be tested in the distribution form."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="STATED_FORM" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraint should be tested in the stated form."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CLOSE_TO_USER_FORM" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraint should be tested in the close to user form."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LONG_NORMAL_FORM" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraint should be tested in the long normal form."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SHORT_NORMAL_FORM" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraint should be tested in the short normal form."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DataType" instanceClassName="com.b2international.snowowl.snomed.snomedrefset.DataType"/>
</ecore:EPackage>
