<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eresource"
    nsURI="http://www.eclipse.org/emf/CDO/Eresource/4.0.0" nsPrefix="eresource">
  <eClassifiers xsi:type="ecore:EClass" name="CDOResourceNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" eType="#//CDOResourceFolder"
        eOpposite="#//CDOResourceFolder/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnType" value="VARCHAR"/>
        <details key="columnLength" value="255"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CDOResourceFolder" eSuperTypes="#//CDOResourceNode">
    <eOperations name="addResourceFolder" eType="#//CDOResourceFolder">
      <eParameters name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="addResource" eType="#//CDOResource">
      <eParameters name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//CDOResourceNode" containment="true" resolveProxies="false" eOpposite="#//CDOResourceNode/folder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CDOResource" eSuperTypes="#//CDOResourceLeaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceSet" eType="#//ResourceSet"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uRI" eType="#//URI" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackingModification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errors" upperBound="-1"
        eType="#//Diagnostic" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warnings" upperBound="-1"
        eType="#//Diagnostic" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStamp" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Diagnostic" instanceClassName="org.eclipse.emf.ecore.resource.Resource.Diagnostic"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="CDOResourceLeaf" abstract="true" eSuperTypes="#//CDOResourceNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CDOFileResource" abstract="true" eSuperTypes="#//CDOResourceLeaf">
    <eOperations name="getContents" lowerBound="1" eType="ecore:EDataType etypes.ecore#//Lob"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CDOBinaryResource" eSuperTypes="#//CDOFileResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" lowerBound="1"
        eType="ecore:EDataType etypes.ecore#//Blob"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CDOTextResource" eSuperTypes="#//CDOFileResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" lowerBound="1"
        eType="ecore:EDataType etypes.ecore#//Clob"/>
  </eClassifiers>
</ecore:EPackage>
