/*
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed.parser.antlr;

import com.b2international.snowowl.snomed.parser.antlr.internal.InternalQLParser;
import com.b2international.snowowl.snomed.services.QLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class QLParser extends AbstractAntlrParser {

	@Inject
	private QLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQLParser createParser(XtextTokenStream stream) {
		return new InternalQLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Query";
	}

	public QLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
