/*
 * Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 10:42:55 AM CET 
//


package org.ihtsdo.sct;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type that represents an MRCM Relationship Test
 * 
 * <p>Java class for CmTestRelationship complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CmTestRelationship">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ihtsdo-org/sct}SifComponent">
 *       &lt;attribute name="refAttributeUid" use="required" type="{urn:ihtsdo-org/sct}Uuid" />
 *       &lt;attribute name="refRangeUid" use="required" type="{urn:ihtsdo-org/sct}Uuid" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CmTestRelationship")
public class CmTestRelationship
    extends SifComponent
{

    @XmlAttribute(name = "refAttributeUid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refAttributeUid;
    @XmlAttribute(name = "refRangeUid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refRangeUid;

    /**
     * Gets the value of the refAttributeUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefAttributeUid() {
        return refAttributeUid;
    }

    /**
     * Sets the value of the refAttributeUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefAttributeUid(String value) {
        this.refAttributeUid = value;
    }

    /**
     * Gets the value of the refRangeUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefRangeUid() {
        return refRangeUid;
    }

    /**
     * Sets the value of the refRangeUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefRangeUid(String value) {
        this.refRangeUid = value;
    }

}