/*
 * Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 10:42:55 AM CET 
//


package org.ihtsdo.sct;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Complex type that represents a set of one or more changes originated by a
 * single source. The changeSet may include nested changeSets from other
 * subsidiary sources. In this case the outer changeSet metadata refers to the
 * aggregator.
 * 
 * <p>Java class for SifChangeSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SifChangeSet">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ihtsdo-org/sct}SifChangeBase">
 *       &lt;sequence>
 *         &lt;element name="comment" type="{urn:ihtsdo-org/sct}CommentMarkup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="source" type="{urn:ihtsdo-org/sct}SifSource"/>
 *         &lt;element name="pathDefinition" type="{urn:ihtsdo-org/sct}SifPathDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="changeSet" type="{urn:ihtsdo-org/sct}SifChangeSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="changes" type="{urn:ihtsdo-org/sct}SifChanges" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "changeSet")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SifChangeSet", propOrder = {
    "comment",
    "source",
    "pathDefinition",
    "changeSet",
    "changes"
})
public class SifChangeSet
    extends SifChangeBase
{

    protected List<CommentMarkup> comment;
    @XmlElement(required = true)
    protected SifSource source;
    protected List<SifPathDefinition> pathDefinition;
    protected List<SifChangeSet> changeSet;
    protected List<SifChanges> changes;

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentMarkup }
     * 
     * 
     */
    public List<CommentMarkup> getComment() {
        if (comment == null) {
            comment = new ArrayList<CommentMarkup>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SifSource }
     *     
     */
    public SifSource getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SifSource }
     *     
     */
    public void setSource(SifSource value) {
        this.source = value;
    }

    /**
     * Gets the value of the pathDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SifPathDefinition }
     * 
     * 
     */
    public List<SifPathDefinition> getPathDefinition() {
        if (pathDefinition == null) {
            pathDefinition = new ArrayList<SifPathDefinition>();
        }
        return this.pathDefinition;
    }

    /**
     * Gets the value of the changeSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SifChangeSet }
     * 
     * 
     */
    public List<SifChangeSet> getChangeSet() {
        if (changeSet == null) {
            changeSet = new ArrayList<SifChangeSet>();
        }
        return this.changeSet;
    }

    /**
     * Gets the value of the changes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChanges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SifChanges }
     * 
     * 
     */
    public List<SifChanges> getChanges() {
        if (changes == null) {
            changes = new ArrayList<SifChanges>();
        }
        return this.changes;
    }

}