/*
 * Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 10:42:55 AM CET 
//


package org.ihtsdo.sct;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Complex type that represents a set of one or more changes originated by a
 * single source. The changeSet may include nested changeSets from other
 * subsidiary sources. In this case the outer changeSet metadata refers to the
 * aggregator.
 * 
 * <p>Java class for SifChange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SifChange">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ihtsdo-org/sct}SifChangeBase">
 *       &lt;sequence>
 *         &lt;element name="comment" type="{urn:ihtsdo-org/sct}CommentMarkup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="before" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{urn:ihtsdo-org/sct}null"/>
 *                   &lt;element ref="{urn:ihtsdo-org/sct}component"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="after">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{urn:ihtsdo-org/sct}null"/>
 *                   &lt;element ref="{urn:ihtsdo-org/sct}component"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SifChange", propOrder = {
    "comment",
    "before",
    "after"
})
public class SifChange
    extends SifChangeBase
{

    protected List<CommentMarkup> comment;
    protected List<SifChange.Before> before;
    @XmlElement(required = true)
    protected SifChange.After after;

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentMarkup }
     * 
     * 
     */
    public List<CommentMarkup> getComment() {
        if (comment == null) {
            comment = new ArrayList<CommentMarkup>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the before property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the before property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBefore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SifChange.Before }
     * 
     * 
     */
    public List<SifChange.Before> getBefore() {
        if (before == null) {
            before = new ArrayList<SifChange.Before>();
        }
        return this.before;
    }

    /**
     * Gets the value of the after property.
     * 
     * @return
     *     possible object is
     *     {@link SifChange.After }
     *     
     */
    public SifChange.After getAfter() {
        return after;
    }

    /**
     * Sets the value of the after property.
     * 
     * @param value
     *     allowed object is
     *     {@link SifChange.After }
     *     
     */
    public void setAfter(SifChange.After value) {
        this.after = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{urn:ihtsdo-org/sct}null"/>
     *         &lt;element ref="{urn:ihtsdo-org/sct}component"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_null",
        "component"
    })
    public static class After {

        @XmlElement(name = "null")
        protected Object _null;
        @XmlElementRef(name = "component", namespace = "urn:ihtsdo-org/sct", type = JAXBElement.class)
        protected JAXBElement<?> component;

        /**
         * Gets the value of the null property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNull() {
            return _null;
        }

        /**
         * Sets the value of the null property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNull(Object value) {
            this._null = value;
        }

        /**
         * Gets the value of the component property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link RefSetMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmNote }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmConstraint }{@code >}
         *     {@link JAXBElement }{@code <}{@link SifComponent }{@code >}
         *     {@link JAXBElement }{@code <}{@link RsmMrcm }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestCardinality }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestDependency }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestRelationship }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmDependencyMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link RefSet }{@code >}
         *     
         */
        public JAXBElement<?> getComponent() {
            return component;
        }

        /**
         * Sets the value of the component property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link RefSetMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmNote }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmConstraint }{@code >}
         *     {@link JAXBElement }{@code <}{@link SifComponent }{@code >}
         *     {@link JAXBElement }{@code <}{@link RsmMrcm }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestCardinality }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestDependency }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestRelationship }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmDependencyMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link RefSet }{@code >}
         *     
         */
        public void setComponent(JAXBElement<?> value) {
            this.component = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{urn:ihtsdo-org/sct}null"/>
     *         &lt;element ref="{urn:ihtsdo-org/sct}component"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_null",
        "component"
    })
    public static class Before {

        @XmlElement(name = "null")
        protected Object _null;
        @XmlElementRef(name = "component", namespace = "urn:ihtsdo-org/sct", type = JAXBElement.class)
        protected JAXBElement<?> component;

        /**
         * Gets the value of the null property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNull() {
            return _null;
        }

        /**
         * Sets the value of the null property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNull(Object value) {
            this._null = value;
        }

        /**
         * Gets the value of the component property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link RefSetMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmNote }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmConstraint }{@code >}
         *     {@link JAXBElement }{@code <}{@link SifComponent }{@code >}
         *     {@link JAXBElement }{@code <}{@link RsmMrcm }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestCardinality }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestDependency }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestRelationship }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmDependencyMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link RefSet }{@code >}
         *     
         */
        public JAXBElement<?> getComponent() {
            return component;
        }

        /**
         * Sets the value of the component property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link RefSetMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmNote }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmConstraint }{@code >}
         *     {@link JAXBElement }{@code <}{@link SifComponent }{@code >}
         *     {@link JAXBElement }{@code <}{@link RsmMrcm }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestCardinality }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestDependency }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmTestRelationship }{@code >}
         *     {@link JAXBElement }{@code <}{@link CmDependencyMember }{@code >}
         *     {@link JAXBElement }{@code <}{@link RefSet }{@code >}
         *     
         */
        public void setComponent(JAXBElement<?> value) {
            this.component = value;
        }

    }

}