/*
 * Copyright 2011-2015 B2i Healthcare Pte Ltd, http://b2i.sg
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *///
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 10:42:55 AM CET 
//


package org.ihtsdo.sct;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type that represents the metadata associated with an MRCM Reference Set.
 * 
 * <p>Java class for SifRefSetMrcm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SifRefSetMrcm">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ihtsdo-org/sct}SifComponent">
 *       &lt;attribute name="name" use="required" type="{urn:ihtsdo-org/sct}Term" />
 *       &lt;attribute name="shortName" type="{urn:ihtsdo-org/sct}ShortTerm" />
 *       &lt;attribute name="refSetType" use="required" type="{urn:ihtsdo-org/sct}RefSetType" />
 *       &lt;attribute name="isExclusion" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isScoped" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isPrioritized" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="memberType" type="{urn:ihtsdo-org/sct}ComponentType" default="0" />
 *       &lt;attribute name="realmId" type="{urn:ihtsdo-org/sct}SctReference" />
 *       &lt;attribute name="domainId" type="{urn:ihtsdo-org/sct}SctReference" />
 *       &lt;attribute name="languageCode" type="{urn:ihtsdo-org/sct}Language" />
 *       &lt;attribute name="annotation" type="{urn:ihtsdo-org/sct}Term" />
 *       &lt;attribute name="originator" type="{urn:ihtsdo-org/sct}SctReference" />
 *       &lt;attribute name="baseRefSetId" type="{urn:ihtsdo-org/sct}SctReference" />
 *       &lt;attribute name="baseRefSetEffectiveTime" type="{urn:ihtsdo-org/sct}UtcTime" />
 *       &lt;attribute name="baseRefSetLatestVersion" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" />
 *       &lt;attribute name="isDomain" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isAttribute" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isRange" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="filter" type="{urn:ihtsdo-org/sct}ExpressionText" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SifRefSetMrcm")
@XmlSeeAlso({
    RefSet.class
})
public class SifRefSetMrcm
    extends SifComponent
{

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "shortName")
    protected String shortName;
    @XmlAttribute(name = "refSetType", required = true)
    protected short refSetType;
    @XmlAttribute(name = "isExclusion")
    protected Boolean isExclusion;
    @XmlAttribute(name = "isScoped")
    protected Boolean isScoped;
    @XmlAttribute(name = "isPrioritized")
    protected Boolean isPrioritized;
    @XmlAttribute(name = "memberType")
    protected Short memberType;
    @XmlAttribute(name = "realmId")
    protected String realmId;
    @XmlAttribute(name = "domainId")
    protected String domainId;
    @XmlAttribute(name = "languageCode")
    protected String languageCode;
    @XmlAttribute(name = "annotation")
    protected String annotation;
    @XmlAttribute(name = "originator")
    protected String originator;
    @XmlAttribute(name = "baseRefSetId")
    protected String baseRefSetId;
    @XmlAttribute(name = "baseRefSetEffectiveTime")
    protected String baseRefSetEffectiveTime;
    @XmlAttribute(name = "baseRefSetLatestVersion")
    protected Boolean baseRefSetLatestVersion;
    @XmlAttribute(name = "isDomain")
    protected Boolean isDomain;
    @XmlAttribute(name = "isAttribute")
    protected Boolean isAttribute;
    @XmlAttribute(name = "isRange")
    protected Boolean isRange;
    @XmlAttribute(name = "filter")
    protected String filter;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the refSetType property.
     * 
     */
    public short getRefSetType() {
        return refSetType;
    }

    /**
     * Sets the value of the refSetType property.
     * 
     */
    public void setRefSetType(short value) {
        this.refSetType = value;
    }

    /**
     * Gets the value of the isExclusion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsExclusion() {
        if (isExclusion == null) {
            return false;
        } else {
            return isExclusion;
        }
    }

    /**
     * Sets the value of the isExclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsExclusion(Boolean value) {
        this.isExclusion = value;
    }

    /**
     * Gets the value of the isScoped property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsScoped() {
        if (isScoped == null) {
            return false;
        } else {
            return isScoped;
        }
    }

    /**
     * Sets the value of the isScoped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsScoped(Boolean value) {
        this.isScoped = value;
    }

    /**
     * Gets the value of the isPrioritized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsPrioritized() {
        if (isPrioritized == null) {
            return false;
        } else {
            return isPrioritized;
        }
    }

    /**
     * Sets the value of the isPrioritized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrioritized(Boolean value) {
        this.isPrioritized = value;
    }

    /**
     * Gets the value of the memberType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public short getMemberType() {
        if (memberType == null) {
            return ((short) 0);
        } else {
            return memberType;
        }
    }

    /**
     * Sets the value of the memberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMemberType(Short value) {
        this.memberType = value;
    }

    /**
     * Gets the value of the realmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealmId() {
        return realmId;
    }

    /**
     * Sets the value of the realmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealmId(String value) {
        this.realmId = value;
    }

    /**
     * Gets the value of the domainId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * Sets the value of the domainId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainId(String value) {
        this.domainId = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the originator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginator(String value) {
        this.originator = value;
    }

    /**
     * Gets the value of the baseRefSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseRefSetId() {
        return baseRefSetId;
    }

    /**
     * Sets the value of the baseRefSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseRefSetId(String value) {
        this.baseRefSetId = value;
    }

    /**
     * Gets the value of the baseRefSetEffectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseRefSetEffectiveTime() {
        return baseRefSetEffectiveTime;
    }

    /**
     * Sets the value of the baseRefSetEffectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseRefSetEffectiveTime(String value) {
        this.baseRefSetEffectiveTime = value;
    }

    /**
     * Gets the value of the baseRefSetLatestVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBaseRefSetLatestVersion() {
        if (baseRefSetLatestVersion == null) {
            return false;
        } else {
            return baseRefSetLatestVersion;
        }
    }

    /**
     * Sets the value of the baseRefSetLatestVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBaseRefSetLatestVersion(Boolean value) {
        this.baseRefSetLatestVersion = value;
    }

    /**
     * Gets the value of the isDomain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDomain() {
        return isDomain;
    }

    /**
     * Sets the value of the isDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDomain(Boolean value) {
        this.isDomain = value;
    }

    /**
     * Gets the value of the isAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAttribute() {
        return isAttribute;
    }

    /**
     * Sets the value of the isAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAttribute(Boolean value) {
        this.isAttribute = value;
    }

    /**
     * Gets the value of the isRange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRange() {
        return isRange;
    }

    /**
     * Sets the value of the isRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRange(Boolean value) {
        this.isRange = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

}