version: '2.2'
services: 
  snowowl:
    image: # TODO: build an image and upload to Docker Hub
    environment:
      SO_JAVA_OPTS: "-Xms2g -Xmx2g"
    container_name: snowowl
    networks:
      - snowowl
    ports:
      - 8080:8080

networks:
  snowowl: