<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="snomed" nsURI="http://b2international.com/snowowl/sct/1.0" nsPrefix="sct">
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnLength" value="19"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Concept">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnName" value="module0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="released" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inactivatable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inactivationIndicatorRefSetMembers"
        upperBound="-1" eType="ecore:EClass ../../com.b2international.snowowl.snomed.refset.model/model/snomedrefset.ecore#//SnomedAttributeValueRefSetMember"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationRefSetMembers"
        upperBound="-1" eType="ecore:EClass ../../com.b2international.snowowl.snomed.refset.model/model/snomedrefset.ecore#//SnomedAssociationRefSetMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotatable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteDomainRefSetMembers"
        upperBound="-1" eType="ecore:EClass ../../com.b2international.snowowl.snomed.refset.model/model/snomedrefset.ecore#//SnomedConcreteDataTypeRefSetMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//Component #//Inactivatable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnType" value="LONG VARCHAR"/>
        <details key="columnLength" value="32768"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//Concept" eOpposite="#//Concept/descriptions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="caseSignificance" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageRefSetMembers"
        upperBound="-1" eType="ecore:EClass ../../com.b2international.snowowl.snomed.refset.model/model/snomedrefset.ecore#//SnomedLanguageRefSetMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept" eSuperTypes="#//Component #//Inactivatable #//Annotatable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionStatus" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundRelationships"
        ordered="false" upperBound="-1" eType="#//Relationship" containment="true"
        eOpposite="#//Relationship/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
        eType="#//Description" containment="true" eOpposite="#//Description/concept"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exhaustive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullySpecifiedName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        transient="true" defaultValueLiteral="" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//Component #//Annotatable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unionGroup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationNegated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Concept" eOpposite="#//Concept/outboundRelationships"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicType" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifier" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinabilityRefSetMembers"
        upperBound="-1" eType="ecore:EClass ../../com.b2international.snowowl.snomed.refset.model/model/snomedrefset.ecore#//SnomedAttributeValueRefSetMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concepts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" ordered="false"
        upperBound="-1" eType="#//Concept" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedRelease" eSuperTypes="../../com.b2international.snowowl.terminologyregistry.model/model/terminologymetadata.ecore#//CodeSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseCodeSystemOID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/CDO/DBStore">
        <details key="columnLength" value="255"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="releaseType" eType="#//SnomedReleaseType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnomedVersion" eSuperTypes="../../com.b2international.snowowl.terminologyregistry.model/model/terminologymetadata.ecore#//CodeSystemVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modules" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SnomedReleaseType">
    <eLiterals name="INTERNATIONAL" literal="INTERNATIONAL"/>
    <eLiterals name="EXTENSION" value="1" literal="EXTENSION"/>
  </eClassifiers>
</ecore:EPackage>
