/*
 * Copyright 2017 B2i Healthcare Pte Ltd, http://b2i.sg
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.b2international.snowowl.snomed.reasoner.server;

import java.util.Set;

import com.b2international.snowowl.snomed.Concept;
import com.b2international.snowowl.snomed.datastore.SnomedEditingContext;
import com.google.common.collect.Multiset;

/**
 * Allocator to create Id namespaces and module concepts to inferred SNOMED CT properties
 * generated by the classifier. To improve performance this allocator provides the means of 
 * pre-fetching namespaces and modules in bulk.
 */
public interface NamespaceAndModuleAssigner {

	/**
	 * Pre-allocate SCTIDs and modules for the new relationships of each concept passed in as a {@link Multiset} of concept ids.
	 * 
	 * The allocated values and modules can be later be retrieved by {@link #getRelationshipId(String)} and
	 * {@link #getRelationshipModule(String)}, respectively. 
	 * 
	 * @param conceptIds the number of relationships to allocate values for, keyed by source concept ID
	 * @param context the active SNOMED CT editing context
	 */
	public void allocateRelationshipIdsAndModules(final Multiset<String> conceptIds, final SnomedEditingContext context);

	/**
	 * Returns an SCTID to be registered to a relationship based on its source concept id and branch path where it is located.
	 * 
	 * @param sourceConceptId concept id of the relationship to allocate the SCTID to
	 * @return SCTID for the relationship
	 */
	public String getRelationshipId(final String sourceConceptId);

	/**
	 * Returns a module concept to be assigned to a relationship based on its source concept id and branch path where it is located.
	 * 
	 * @param source concept id of the relationship to allocate the namespace to
	 * @return module concept id for the relationship
	 */
	public Concept getRelationshipModule(final String sourceConceptId);
	
	/**
	 * Pre-allocate modules for the new concrete domains of each concept passed in as a set of concept ids.
	 * The allocated modules can be later distributed by the {@link #getConcreteDomainModule(String)} method.
	 * 
	 * @param conceptIds the set of source concept ids to use for pre-allocation
	 * @param context the active SNOMED CT editing context
	 */
	public void allocateConcreteDomainModules(final Set<String> conceptIds, final SnomedEditingContext context);

	/**
	 * Returns a module concept to be assigned to a concrete domain based on its source concept id and branch path where it is located.
	 * 
	 * @param source concept id of the concrete domain to allocate the namespace to
	 * @return module concept id for the concrete domain
	 */
	public Concept getConcreteDomainModule(final String sourceConceptId);
}
