<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="escg"
    nsURI="http://www.b2international.com/snowowl/dsl/ESCG" nsPrefix="escg">
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpression" upperBound="-1"
        eType="#//SubExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lValues" upperBound="-1"
        eType="#//LValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" eType="#//Refinements"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LValue" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefSet" eSuperTypes="#//LValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptGroup" eSuperTypes="#//LValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" eType="#//Concept"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refinements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeSet" eType="#//AttributeSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeGroups" upperBound="-1"
        eType="#//AttributeGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSet" eSuperTypes="#//AttributeGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" eType="#//AttributeAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptAssignment" eSuperTypes="#//AttributeAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//LValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//RValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericalAssignment" eSuperTypes="#//AttributeAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Concept"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericalAssignmentGroup" eSuperTypes="#//AttributeAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredientConcept" eType="#//Concept"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substance" eType="#//RValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numericValue" eType="#//NumericalAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegatableSubExpression" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//RValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//RValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//RValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//RValue"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
