/*
 * generated by Xtext 2.11.0
 */
package com.b2international.snowowl.snomed.scoping;

import com.b2international.snowowl.snomed.ecl.scoping.EclScopeProvider;

public abstract class AbstractQLScopeProvider extends EclScopeProvider {
}
