<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="queryast"
    nsURI="http://www.b2international.com/snowowl/dsl/ast" nsPrefix="ast">
  <eClassifiers xsi:type="ecore:EClass" name="RValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryRValue" abstract="true" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//RValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryRValue" abstract="true" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//RValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//RValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptRef" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" lowerBound="1"
        eType="#//SubsumptionQuantifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefSet" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotClause" eSuperTypes="#//UnaryRValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubExpression" eSuperTypes="#//UnaryRValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndClause" eSuperTypes="#//BinaryRValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrClause" eSuperTypes="#//BinaryRValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeClause" eSuperTypes="#//BinaryRValue"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SubsumptionQuantifier">
    <eLiterals name="SELF"/>
    <eLiterals name="ANY_SUBTYPE" value="1"/>
    <eLiterals name="SELF_AND_ANY_SUBTYPE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeClauseGroup" eSuperTypes="#//UnaryRValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericDataClause" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" eType="#//RValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericDataGroupClause" eSuperTypes="#//RValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" eType="#//RValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numericData" lowerBound="1"
        eType="#//NumericDataClause"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substance" lowerBound="1"
        eType="#//RValue"/>
  </eClassifiers>
</ecore:EPackage>
